### ISSUE TITLE
Cache Mesh local AABB

### ISSUE THREAD

**Issue by lassade** [aevyrie/bevy_mod_bounding#3]
Caching the local AABB it's faster than recalculating it from the mesh vertices every time the `GlobalTransform` changes; 

1. If a mesh is created or modified, create/recalculate the local AABB;
2. When the transform or the local AABB changes recalculate the world AABB;

The same principle can be applied to all other primitives;

Side note:
This example will be much better of if `GlobalTransform` was actually a Mat4, the further I think global TRS is a 'convenience' that will hurt perf in long term;

**Comment by aevyrie** [comment]
The OBB has this behavior - it computes the OBB for the mesh locally one time, and only updates if the mesh changes. The bevy transform propagation system handles the rest.

I'm planning on writing an RFC for bounding boxes in bevy using what I've learned here, and we can collaborate on a design.
